name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Release
        uses: threeal/cmake-action@v2.1.0

      - name: Find EXE
        shell: pwsh
        run: |
          Get-ChildItem -Path build -Recurse -Filter *.exe

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: flxengine-windows-x64
          path: build/**/*.exe